<?xml version="1.0" encoding="UTF-8" ?>
<Package name="template" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="start_template" xar="behavior.xar" />
        <BehaviorDescription name="behavior" src="animations/little_laugh" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs>
        <Dialog name="dlg_welcome" src="dlg_welcome/dlg_welcome.dlg" />
    </Dialogs>
    <Resources>
        <File name="index" src="html/index.html" />
        <File name="jquery.min" src="html/js/jquery.min.js" />
        <File name="main" src="html/js/main.js" />
        <File name="robotutils" src="html/js/robotutils.js" />
        <File name="Enu_Ono_Laugh_Happy_2_pitch_115" src="sounds/Enu_Ono_Laugh_Happy_2_pitch_115.ogg" />
        <File name="app" src="html/css/app.css" />
        <File name="99" src="html/img/99.png" />
        <File name="aliens_guy" src="html/img/aliens_guy.jpg" />
        <File name="all_the_things" src="html/img/all_the_things.jpg" />
        <File name="alot" src="html/img/alot.png" />
        <File name="america" src="html/img/america.gif" />
        <File name="approved" src="html/img/approved.png" />
        <File name="atom" src="html/img/atom.png" />
        <File name="atom_editor" src="html/img/atom_editor.png" />
        <File name="auae" src="html/img/auae.png" />
        <File name="aussie_conga_parrot" src="html/img/aussie_conga_parrot.gif" />
        <File name="avocado_toast" src="html/img/avocado_toast.png" />
        <File name="aw_thanks" src="html/img/aw_thanks.png" />
        <File name="awkward_seal" src="html/img/awkward_seal.jpg" />
        <File name="aws" src="html/img/aws.png" />
        <File name="babel_fish" src="html/img/babel_fish.jpg" />
        <File name="bad_pun_dog" src="html/img/bad_pun_dog.png" />
        <File name="ball_of_yarn" src="html/img/ball_of_yarn.png" />
        <File name="banana_dance" src="html/img/banana_dance.gif" />
        <File name="banana_parrot" src="html/img/banana_parrot.gif" />
        <File name="beachball" src="html/img/beachball.gif" />
        <File name="bender" src="html/img/bender.gif" />
        <File name="beret_parrot" src="html/img/beret_parrot.gif" />
        <File name="biking" src="html/img/biking.gif" />
        <File name="bill_nye" src="html/img/bill_nye.gif" />
        <File name="bitbucket" src="html/img/bitbucket.png" />
        <File name="black_lightsaber" src="html/img/black_lightsaber.png" />
        <File name="blonde_sassy_parrot" src="html/img/blonde_sassy_parrot.gif" />
        <File name="blue_lightsaber" src="html/img/blue_lightsaber.png" />
        <File name="blue_ribbon" src="html/img/blue_ribbon.png" />
        <File name="blue_steel" src="html/img/blue_steel.gif" />
        <File name="blue_troll" src="html/img/blue_troll.gif" />
        <File name="bob_ross" src="html/img/bob_ross.png" />
        <File name="bounce" src="html/img/bounce.gif" />
        <File name="bowie_labrynth" src="html/img/bowie_labrynth.jpg" />
        <File name="brace_yourselves" src="html/img/brace_yourselves.jpg" />
        <File name="bunchie" src="html/img/bunchie.gif" />
        <File name="bushes_reverse" src="html/img/bushes_reverse.gif" />
        <File name="business_cat" src="html/img/business_cat.jpg" />
        <File name="butter_croissant" src="html/img/butter_croissant.png" />
        <File name="caffeine_wow" src="html/img/caffeine_wow.jpg" />
        <File name="captain_obvious" src="html/img/captain_obvious.png" />
        <File name="cat_typing" src="html/img/cat_typing.gif" />
        <File name="ceiling_parrot" src="html/img/ceiling_parrot.gif" />
        <File name="celebrate" src="html/img/celebrate.gif" />
        <File name="challenge_accepted" src="html/img/challenge_accepted.jpg" />
        <File name="champagne" src="html/img/champagne.gif" />
        <File name="christmas_parrot" src="html/img/christmas_parrot.gif" />
        <File name="christmas_poop" src="html/img/christmas_poop.jpg" />
        <File name="chrome" src="html/img/chrome.png" />
        <File name="clapping_all_hands" src="html/img/clapping_all_hands.gif" />
        <File name="clippy" src="html/img/clippy.png" />
        <File name="coffee_parrot" src="html/img/coffee_parrot.gif" />
        <File name="com_badge" src="html/img/com_badge.png" />
        <File name="confluence" src="html/img/confluence.png" />
        <File name="confused_nick_young" src="html/img/confused_nick_young.png" />
        <File name="confused_parrot" src="html/img/confused_parrot.gif" />
        <File name="conga_parrot" src="html/img/conga_parrot.gif" />
        <File name="cool_beans" src="html/img/cool_beans.png" />
        <File name="cool_doge" src="html/img/cool_doge.gif" />
        <File name="cool_koala" src="html/img/cool_koala.jpg" />
        <File name="cool_shakespeare" src="html/img/cool_shakespeare.png" />
        <File name="coop" src="html/img/coop.png" />
        <File name="cowboy" src="html/img/cowboy.jpeg" />
        <File name="crickets" src="html/img/crickets.gif" />
        <File name="da_real_mvp" src="html/img/da_real_mvp.png" />
        <File name="dabbing_unicorn" src="html/img/dabbing_unicorn.png" />
        <File name="dancing_corgi" src="html/img/dancing_corgi.gif" />
        <File name="dark_helmet" src="html/img/dark_helmet.jpg" />
        <File name="deal_with_it_parrot" src="html/img/deal_with_it_parrot.gif" />
        <File name="denied" src="html/img/denied.png" />
        <File name="dirk" src="html/img/dirk.png" />
        <File name="disco_dance" src="html/img/disco_dance.gif" />
        <File name="disco_parrot" src="html/img/disco_parrot.gif" />
        <File name="ditto" src="html/img/ditto.png" />
        <File name="doge" src="html/img/doge.png" />
        <File name="doge_tea" src="html/img/doge_tea.jpg" />
        <File name="dogecoin" src="html/img/dogecoin.png" />
        <File name="donut_parrot" src="html/img/donut_parrot.gif" />
        <File name="dumpster_fire" src="html/img/dumpster_fire.gif" />
        <File name="dumpster_flyer" src="html/img/dumpster_flyer.gif" />
        <File name="eevee" src="html/img/eevee.png" />
        <File name="emacs" src="html/img/emacs.png" />
        <File name="energizer_bunny" src="html/img/energizer_bunny.gif" />
        <File name="evil_lightsaber" src="html/img/evil_lightsaber.png" />
        <File name="excellent" src="html/img/excellent.png" />
        <File name="excellent_mr_burns" src="html/img/excellent_mr_burns.gif" />
        <File name="explody_parrot" src="html/img/explody_parrot.gif" />
        <File name="facebook" src="html/img/facebook.png" />
        <File name="fb-wow" src="html/img/fb-wow.gif" />
        <File name="fingers_crossed" src="html/img/fingers_crossed.gif" />
        <File name="firefox" src="html/img/firefox.png" />
        <File name="first_world_problems" src="html/img/first_world_problems.gif" />
        <File name="flex" src="html/img/flex.gif" />
        <File name="floof" src="html/img/floof.jpg" />
        <File name="flying_cat" src="html/img/flying_cat.gif" />
        <File name="flying_money_parrot" src="html/img/flying_money_parrot.gif" />
        <File name="flying_money_with_wings" src="html/img/flying_money_with_wings.gif" />
        <File name="flying_spaghetti_monster" src="html/img/flying_spaghetti_monster.png" />
        <File name="forever_alone" src="html/img/forever_alone.png" />
        <File name="fry" src="html/img/fry.png" />
        <File name="gandalf" src="html/img/gandalf.gif" />
        <File name="gasp" src="html/img/gasp.png" />
        <File name="gentleman_parrot" src="html/img/gentleman_parrot.gif" />
        <File name="git" src="html/img/git.png" />
        <File name="gitlab" src="html/img/gitlab.png" />
        <File name="gnome" src="html/img/gnome.png" />
        <File name="gollum" src="html/img/gollum.png" />
        <File name="goose" src="html/img/goose.png" />
        <File name="graphql" src="html/img/graphql.png" />
        <File name="groot" src="html/img/groot.gif" />
        <File name="grumpy_cat" src="html/img/grumpy_cat.png" />
        <File name="hackers" src="html/img/hackers.png" />
        <File name="hammer_time" src="html/img/hammer_time.gif" />
        <File name="hangglider" src="html/img/hangglider.png" />
        <File name="harambe" src="html/img/harambe.png" />
        <File name="harry_potter_parrot" src="html/img/harry_potter_parrot.gif" />
        <File name="heisencat" src="html/img/heisencat.png" />
        <File name="heroku" src="html/img/heroku.png" />
        <File name="hide_the_pain_harold" src="html/img/hide_the_pain_harold.png" />
        <File name="hipster_oversized_glasses" src="html/img/hipster_oversized_glasses.png" />
        <File name="homer_disappear" src="html/img/homer_disappear.gif" />
        <File name="horrified" src="html/img/horrified.png" />
        <File name="how_about_sloth" src="html/img/how_about_sloth.gif" />
        <File name="hulk" src="html/img/hulk.png" />
        <File name="hypnotoad" src="html/img/hypnotoad.gif" />
        <File name="illuminati_confirmed" src="html/img/illuminati_confirmed.png" />
        <File name="in_n_out" src="html/img/in_n_out.jpg" />
        <File name="infinity" src="html/img/infinity.png" />
        <File name="instagram" src="html/img/instagram.png" />
        <File name="invisible_parrot" src="html/img/invisible_parrot.gif" />
        <File name="j_scrabble" src="html/img/j_scrabble.jpg" />
        <File name="jar_jar_binks" src="html/img/jar_jar_binks.png" />
        <File name="jedi_parrot" src="html/img/jedi_parrot.gif" />
        <File name="jetpacktocat" src="html/img/jetpacktocat.png" />
        <File name="jira" src="html/img/jira.png" />
        <File name="jung_von_matt" src="html/img/jung_von_matt.jpg" />
        <File name="kakao_angry_peach" src="html/img/kakao_angry_peach.png" />
        <File name="kakao_apeach_dance" src="html/img/kakao_apeach_dance.png" />
        <File name="kakao_give_up_on_life" src="html/img/kakao_give_up_on_life.png" />
        <File name="kakao_nooo" src="html/img/kakao_nooo.png" />
        <File name="kakao_sassy" src="html/img/kakao_sassy.png" />
        <File name="kakao_sorry" src="html/img/kakao_sorry.png" />
        <File name="kakao_tick_tock" src="html/img/kakao_tick_tock.png" />
        <File name="kermit_tea" src="html/img/kermit_tea.png" />
        <File name="kewl" src="html/img/kewl.gif" />
        <File name="khan" src="html/img/khan.gif" />
        <File name="kilt_bagpipe" src="html/img/kilt_bagpipe.png" />
        <File name="koolaid_man" src="html/img/koolaid_man.png" />
        <File name="lacroix" src="html/img/lacroix.png" />
        <File name="lalala" src="html/img/lalala.gif" />
        <File name="limecat" src="html/img/limecat.png" />
        <File name="link_catch" src="html/img/link_catch.jpg" />
        <File name="link_wave" src="html/img/link_wave.png" />
        <File name="love_parrot" src="html/img/love_parrot.gif" />
        <File name="luxemburgerli" src="html/img/luxemburgerli.png" />
        <File name="make_it_so" src="html/img/make_it_so.gif" />
        <File name="make_it_work" src="html/img/make_it_work.jpg" />
        <File name="mario" src="html/img/mario.gif" />
        <File name="mcgonagall_clapping" src="html/img/mcgonagall_clapping.gif" />
        <File name="meerkat" src="html/img/meerkat.gif" />
        <File name="mic_drop" src="html/img/mic_drop.gif" />
        <File name="microsoft" src="html/img/microsoft.jpg" />
        <File name="middle_parrot" src="html/img/middle_parrot.gif" />
        <File name="mighty_mouse" src="html/img/mighty_mouse.png" />
        <File name="mind_blown" src="html/img/mind_blown.gif" />
        <File name="most_interesting_man" src="html/img/most_interesting_man.png" />
        <File name="murrica" src="html/img/murrica.jpg" />
        <File name="my_little_octocat" src="html/img/my_little_octocat.png" />
        <File name="n64" src="html/img/n64.gif" />
        <File name="neo" src="html/img/neo.png" />
        <File name="nike_swoosh" src="html/img/nike_swoosh.png" />
        <File name="ninja" src="html/img/ninja.gif" />
        <File name="ninja_turtle" src="html/img/ninja_turtle.png" />
        <File name="no" src="html/img/no.png" />
        <File name="no_dice" src="html/img/no_dice.png" />
        <File name="nope-min" src="html/img/nope-min.gif" />
        <File name="nope" src="html/img/nope.gif" />
        <File name="nope_nope_nope" src="html/img/nope_nope_nope.gif" />
        <File name="npm" src="html/img/npm.png" />
        <File name="nyan_parrot" src="html/img/nyan_parrot.gif" />
        <File name="octocat" src="html/img/octocat.png" />
        <File name="octocat_gentleman_dev" src="html/img/octocat_gentleman_dev.jpg" />
        <File name="octocat_lady_dev" src="html/img/octocat_lady_dev.png" />
        <File name="octocat_lady_dev_brunette" src="html/img/octocat_lady_dev_brunette.png" />
        <File name="oktobercat" src="html/img/oktobercat.png" />
        <File name="on_off_switch" src="html/img/on_off_switch.jpg" />
        <File name="one_does_not_simply" src="html/img/one_does_not_simply.png" />
        <File name="opera" src="html/img/opera.png" />
        <File name="papal_parrot" src="html/img/papal_parrot.gif" />
        <File name="paraglider" src="html/img/paraglider.png" />
        <File name="parrot_lift_off" src="html/img/parrot_lift_off.gif" />
        <File name="party_aw_yeah" src="html/img/party_aw_yeah.gif" />
        <File name="party_corgi" src="html/img/party_corgi.gif" />
        <File name="party_crying_blood" src="html/img/party_crying_blood.gif" />
        <File name="party_dinosaur" src="html/img/party_dinosaur.gif" />
        <File name="party_docker" src="html/img/party_docker.gif" />
        <File name="party_dumpster_fire" src="html/img/party_dumpster_fire.gif" />
        <File name="party_frog" src="html/img/party_frog.gif" />
        <File name="party_otter_dance" src="html/img/party_otter_dance.gif" />
        <File name="party_porg" src="html/img/party_porg.gif" />
        <File name="party_trash_dove" src="html/img/party_trash_dove.gif" />
        <File name="party_turtle" src="html/img/party_turtle.gif" />
        <File name="party_wizard" src="html/img/party_wizard.gif" />
        <File name="pepe" src="html/img/pepe.png" />
        <File name="pepechu" src="html/img/pepechu.jpg" />
        <File name="philosoraptor" src="html/img/philosoraptor.png" />
        <File name="pillow" src="html/img/pillow.jpg" />
        <File name="pink_troll" src="html/img/pink_troll.png" />
        <File name="pinky_up" src="html/img/pinky_up.gif" />
        <File name="plus_one" src="html/img/plus_one.png" />
        <File name="pope" src="html/img/pope.png" />
        <File name="pope_francis" src="html/img/pope_francis.png" />
        <File name="portal_parrot" src="html/img/portal_parrot.gif" />
        <File name="postgresql" src="html/img/postgresql.png" />
        <File name="pug" src="html/img/pug.gif" />
        <File name="pumpkin_parrot" src="html/img/pumpkin_parrot.gif" />
        <File name="pusheen_dancing" src="html/img/pusheen_dancing.gif" />
        <File name="python" src="html/img/python.png" />
        <File name="raccoon_water_harp" src="html/img/raccoon_water_harp.gif" />
        <File name="rage" src="html/img/rage.jpg" />
        <File name="raised_eyebrow" src="html/img/raised_eyebrow.png" />
        <File name="raptor_disagrees" src="html/img/raptor_disagrees.gif" />
        <File name="react" src="html/img/react.png" />
        <File name="red_siren" src="html/img/red_siren.gif" />
        <File name="release_the_kraken" src="html/img/release_the_kraken.gif" />
        <File name="reverse_aussie_conga_parrot" src="html/img/reverse_aussie_conga_parrot.gif" />
        <File name="reverse_conga_parrot" src="html/img/reverse_conga_parrot.gif" />
        <File name="revolution_parrot" src="html/img/revolution_parrot.gif" />
        <File name="rickshaw" src="html/img/rickshaw.gif" />
        <File name="rock_nod" src="html/img/rock_nod.gif" />
        <File name="round_of_applause" src="html/img/round_of_applause.gif" />
        <File name="rubber-stamp" src="html/img/rubber-stamp.png" />
        <File name="rubber_duck" src="html/img/rubber_duck.png" />
        <File name="sad_pepe" src="html/img/sad_pepe.png" />
        <File name="safari" src="html/img/safari.png" />
        <File name="sailor_pusheen" src="html/img/sailor_pusheen.gif" />
        <File name="salmon_says" src="html/img/salmon_says.jpg" />
        <File name="saltbae" src="html/img/saltbae.gif" />
        <File name="salute" src="html/img/salute.png" />
        <File name="saturo" src="html/img/saturo.jpg" />
        <File name="science_parrot" src="html/img/science_parrot.gif" />
        <File name="shaka" src="html/img/shaka.png" />
        <File name="shakespeare" src="html/img/shakespeare.png" />
        <File name="shaking_angry_fist" src="html/img/shaking_angry_fist.gif" />
        <File name="ship_it_parrot" src="html/img/ship_it_parrot.gif" />
        <File name="shipping_shipping_ships" src="html/img/shipping_shipping_ships.jpg" />
        <File name="sith_parrot" src="html/img/sith_parrot.gif" />
        <File name="skateboarding" src="html/img/skateboarding.jpg" />
        <File name="skeptical" src="html/img/skeptical.png" />
        <File name="sketch" src="html/img/sketch.png" />
        <File name="ski_parrot" src="html/img/ski_parrot.gif" />
        <File name="snapchat" src="html/img/snapchat.jpg" />
        <File name="snow_octocat" src="html/img/snow_octocat.png" />
        <File name="sonic" src="html/img/sonic.gif" />
        <File name="sonic_waiting" src="html/img/sonic_waiting.gif" />
        <File name="sonos" src="html/img/sonos.png" />
        <File name="spicey" src="html/img/spicey.png" />
        <File name="spotify" src="html/img/spotify.png" />
        <File name="stable_parrot" src="html/img/stable_parrot.gif" />
        <File name="stack_overflow" src="html/img/stack_overflow.png" />
        <File name="starfleet" src="html/img/starfleet.png" />
        <File name="stop" src="html/img/stop.gif" />
        <File name="stop_sign" src="html/img/stop_sign.png" />
        <File name="success-kid" src="html/img/success-kid.png" />
        <File name="such_semantic" src="html/img/such_semantic.jpg" />
        <File name="super_girl" src="html/img/super_girl.png" />
        <File name="superman" src="html/img/superman.gif" />
        <File name="superman_sheild" src="html/img/superman_sheild.jpg" />
        <File name="swiss-fondue" src="html/img/swiss-fondue.png" />
        <File name="tableflip" src="html/img/tableflip.gif" />
        <File name="taion" src="html/img/taion.png" />
        <File name="take_my_money" src="html/img/take_my_money.png" />
        <File name="teamwork" src="html/img/teamwork.png" />
        <File name="that" src="html/img/that.gif" />
        <File name="this" src="html/img/this.gif" />
        <File name="this_is_a_wug" src="html/img/this_is_a_wug.gif" />
        <File name="this_is_fine" src="html/img/this_is_fine.png" />
        <File name="thumbsup_parrot" src="html/img/thumbsup_parrot.gif" />
        <File name="tiziana" src="html/img/tiziana.jpg" />
        <File name="totes_magoats" src="html/img/totes_magoats.gif" />
        <File name="totoro" src="html/img/totoro.gif" />
        <File name="train_wreck" src="html/img/train_wreck.gif" />
        <File name="transparront" src="html/img/transparront.gif" />
        <File name="trap" src="html/img/trap.png" />
        <File name="trex" src="html/img/trex.gif" />
        <File name="troll" src="html/img/troll.png" />
        <File name="troll_doll" src="html/img/troll_doll.png" />
        <File name="troll_parrot" src="html/img/troll_parrot.gif" />
        <File name="trolldance" src="html/img/trolldance.gif" />
        <File name="tumbleweed" src="html/img/tumbleweed.gif" />
        <File name="twitter" src="html/img/twitter.png" />
        <File name="verified" src="html/img/verified.png" />
        <File name="wacky_waving_inflatable_tube_man" src="html/img/wacky_waving_inflatable_tube_man.gif" />
        <File name="wacky_waving_inflatable_tube_man_america" src="html/img/wacky_waving_inflatable_tube_man_america.gif" />
        <File name="wacky_waving_inflatable_tube_man_salmon" src="html/img/wacky_waving_inflatable_tube_man_salmon.gif" />
        <File name="watch_out" src="html/img/watch_out.png" />
        <File name="webpack" src="html/img/webpack.png" />
        <File name="whoa" src="html/img/whoa.jpg" />
        <File name="witness_protection_parrot" src="html/img/witness_protection_parrot.gif" />
        <File name="wonder_woman" src="html/img/wonder_woman.jpg" />
        <File name="wtf_jackie_chan" src="html/img/wtf_jackie_chan.jpg" />
        <File name="ya_rly" src="html/img/ya_rly.png" />
        <File name="yes" src="html/img/yes.png" />
        <File name="yes_sir" src="html/img/yes_sir.gif" />
        <File name="yo_dawg" src="html/img/yo_dawg.png" />
        <File name="yoda" src="html/img/yoda.jpeg" />
        <File name="yoshi" src="html/img/yoshi.gif" />
        <File name="youtube" src="html/img/youtube.png" />
        <File name="zeplin" src="html/img/zeplin.png" />
        <File name="zoidberg" src="html/img/zoidberg.jpg" />
        <File name="app" src="html/js/app.js" />
        <File name="init" src="html/js/init.js" />
        <File name="app" src="html_src/app.js" />
        <File name="App" src="html_src/components/App.js" />
        <File name="global" src="html_src/global.css" />
        <File name="index" src="html_src/index.html" />
        <File name="package-lock" src="html_src/package-lock.json" />
        <File name="package" src="html_src/package.json" />
        <File name="99" src="html_src/public/img/99.png" />
        <File name="aliens_guy" src="html_src/public/img/aliens_guy.jpg" />
        <File name="all_the_things" src="html_src/public/img/all_the_things.jpg" />
        <File name="alot" src="html_src/public/img/alot.png" />
        <File name="america" src="html_src/public/img/america.gif" />
        <File name="approved" src="html_src/public/img/approved.png" />
        <File name="atom" src="html_src/public/img/atom.png" />
        <File name="atom_editor" src="html_src/public/img/atom_editor.png" />
        <File name="auae" src="html_src/public/img/auae.png" />
        <File name="aussie_conga_parrot" src="html_src/public/img/aussie_conga_parrot.gif" />
        <File name="avocado_toast" src="html_src/public/img/avocado_toast.png" />
        <File name="aw_thanks" src="html_src/public/img/aw_thanks.png" />
        <File name="awkward_seal" src="html_src/public/img/awkward_seal.jpg" />
        <File name="aws" src="html_src/public/img/aws.png" />
        <File name="babel_fish" src="html_src/public/img/babel_fish.jpg" />
        <File name="bad_pun_dog" src="html_src/public/img/bad_pun_dog.png" />
        <File name="ball_of_yarn" src="html_src/public/img/ball_of_yarn.png" />
        <File name="banana_dance" src="html_src/public/img/banana_dance.gif" />
        <File name="banana_parrot" src="html_src/public/img/banana_parrot.gif" />
        <File name="beachball" src="html_src/public/img/beachball.gif" />
        <File name="bender" src="html_src/public/img/bender.gif" />
        <File name="beret_parrot" src="html_src/public/img/beret_parrot.gif" />
        <File name="biking" src="html_src/public/img/biking.gif" />
        <File name="bill_nye" src="html_src/public/img/bill_nye.gif" />
        <File name="bitbucket" src="html_src/public/img/bitbucket.png" />
        <File name="black_lightsaber" src="html_src/public/img/black_lightsaber.png" />
        <File name="blonde_sassy_parrot" src="html_src/public/img/blonde_sassy_parrot.gif" />
        <File name="blue_lightsaber" src="html_src/public/img/blue_lightsaber.png" />
        <File name="blue_ribbon" src="html_src/public/img/blue_ribbon.png" />
        <File name="blue_steel" src="html_src/public/img/blue_steel.gif" />
        <File name="blue_troll" src="html_src/public/img/blue_troll.gif" />
        <File name="bob_ross" src="html_src/public/img/bob_ross.png" />
        <File name="bounce" src="html_src/public/img/bounce.gif" />
        <File name="bowie_labrynth" src="html_src/public/img/bowie_labrynth.jpg" />
        <File name="brace_yourselves" src="html_src/public/img/brace_yourselves.jpg" />
        <File name="bunchie" src="html_src/public/img/bunchie.gif" />
        <File name="bushes_reverse" src="html_src/public/img/bushes_reverse.gif" />
        <File name="business_cat" src="html_src/public/img/business_cat.jpg" />
        <File name="butter_croissant" src="html_src/public/img/butter_croissant.png" />
        <File name="caffeine_wow" src="html_src/public/img/caffeine_wow.jpg" />
        <File name="captain_obvious" src="html_src/public/img/captain_obvious.png" />
        <File name="cat_typing" src="html_src/public/img/cat_typing.gif" />
        <File name="ceiling_parrot" src="html_src/public/img/ceiling_parrot.gif" />
        <File name="celebrate" src="html_src/public/img/celebrate.gif" />
        <File name="challenge_accepted" src="html_src/public/img/challenge_accepted.jpg" />
        <File name="champagne" src="html_src/public/img/champagne.gif" />
        <File name="christmas_parrot" src="html_src/public/img/christmas_parrot.gif" />
        <File name="christmas_poop" src="html_src/public/img/christmas_poop.jpg" />
        <File name="chrome" src="html_src/public/img/chrome.png" />
        <File name="clapping_all_hands" src="html_src/public/img/clapping_all_hands.gif" />
        <File name="clippy" src="html_src/public/img/clippy.png" />
        <File name="coffee_parrot" src="html_src/public/img/coffee_parrot.gif" />
        <File name="com_badge" src="html_src/public/img/com_badge.png" />
        <File name="confluence" src="html_src/public/img/confluence.png" />
        <File name="confused_nick_young" src="html_src/public/img/confused_nick_young.png" />
        <File name="confused_parrot" src="html_src/public/img/confused_parrot.gif" />
        <File name="conga_parrot" src="html_src/public/img/conga_parrot.gif" />
        <File name="cool_beans" src="html_src/public/img/cool_beans.png" />
        <File name="cool_doge" src="html_src/public/img/cool_doge.gif" />
        <File name="cool_koala" src="html_src/public/img/cool_koala.jpg" />
        <File name="cool_shakespeare" src="html_src/public/img/cool_shakespeare.png" />
        <File name="coop" src="html_src/public/img/coop.png" />
        <File name="cowboy" src="html_src/public/img/cowboy.jpeg" />
        <File name="crickets" src="html_src/public/img/crickets.gif" />
        <File name="da_real_mvp" src="html_src/public/img/da_real_mvp.png" />
        <File name="dabbing_unicorn" src="html_src/public/img/dabbing_unicorn.png" />
        <File name="dancing_corgi" src="html_src/public/img/dancing_corgi.gif" />
        <File name="dark_helmet" src="html_src/public/img/dark_helmet.jpg" />
        <File name="deal_with_it_parrot" src="html_src/public/img/deal_with_it_parrot.gif" />
        <File name="denied" src="html_src/public/img/denied.png" />
        <File name="dirk" src="html_src/public/img/dirk.png" />
        <File name="disco_dance" src="html_src/public/img/disco_dance.gif" />
        <File name="disco_parrot" src="html_src/public/img/disco_parrot.gif" />
        <File name="ditto" src="html_src/public/img/ditto.png" />
        <File name="doge" src="html_src/public/img/doge.png" />
        <File name="doge_tea" src="html_src/public/img/doge_tea.jpg" />
        <File name="dogecoin" src="html_src/public/img/dogecoin.png" />
        <File name="donut_parrot" src="html_src/public/img/donut_parrot.gif" />
        <File name="dumpster_fire" src="html_src/public/img/dumpster_fire.gif" />
        <File name="dumpster_flyer" src="html_src/public/img/dumpster_flyer.gif" />
        <File name="eevee" src="html_src/public/img/eevee.png" />
        <File name="emacs" src="html_src/public/img/emacs.png" />
        <File name="energizer_bunny" src="html_src/public/img/energizer_bunny.gif" />
        <File name="evil_lightsaber" src="html_src/public/img/evil_lightsaber.png" />
        <File name="excellent" src="html_src/public/img/excellent.png" />
        <File name="excellent_mr_burns" src="html_src/public/img/excellent_mr_burns.gif" />
        <File name="explody_parrot" src="html_src/public/img/explody_parrot.gif" />
        <File name="facebook" src="html_src/public/img/facebook.png" />
        <File name="fb-wow" src="html_src/public/img/fb-wow.gif" />
        <File name="fingers_crossed" src="html_src/public/img/fingers_crossed.gif" />
        <File name="firefox" src="html_src/public/img/firefox.png" />
        <File name="first_world_problems" src="html_src/public/img/first_world_problems.gif" />
        <File name="flex" src="html_src/public/img/flex.gif" />
        <File name="floof" src="html_src/public/img/floof.jpg" />
        <File name="flying_cat" src="html_src/public/img/flying_cat.gif" />
        <File name="flying_money_parrot" src="html_src/public/img/flying_money_parrot.gif" />
        <File name="flying_money_with_wings" src="html_src/public/img/flying_money_with_wings.gif" />
        <File name="flying_spaghetti_monster" src="html_src/public/img/flying_spaghetti_monster.png" />
        <File name="forever_alone" src="html_src/public/img/forever_alone.png" />
        <File name="fry" src="html_src/public/img/fry.png" />
        <File name="gandalf" src="html_src/public/img/gandalf.gif" />
        <File name="gasp" src="html_src/public/img/gasp.png" />
        <File name="gentleman_parrot" src="html_src/public/img/gentleman_parrot.gif" />
        <File name="git" src="html_src/public/img/git.png" />
        <File name="gitlab" src="html_src/public/img/gitlab.png" />
        <File name="gnome" src="html_src/public/img/gnome.png" />
        <File name="gollum" src="html_src/public/img/gollum.png" />
        <File name="goose" src="html_src/public/img/goose.png" />
        <File name="graphql" src="html_src/public/img/graphql.png" />
        <File name="groot" src="html_src/public/img/groot.gif" />
        <File name="grumpy_cat" src="html_src/public/img/grumpy_cat.png" />
        <File name="hackers" src="html_src/public/img/hackers.png" />
        <File name="hammer_time" src="html_src/public/img/hammer_time.gif" />
        <File name="hangglider" src="html_src/public/img/hangglider.png" />
        <File name="harambe" src="html_src/public/img/harambe.png" />
        <File name="harry_potter_parrot" src="html_src/public/img/harry_potter_parrot.gif" />
        <File name="heisencat" src="html_src/public/img/heisencat.png" />
        <File name="heroku" src="html_src/public/img/heroku.png" />
        <File name="hide_the_pain_harold" src="html_src/public/img/hide_the_pain_harold.png" />
        <File name="hipster_oversized_glasses" src="html_src/public/img/hipster_oversized_glasses.png" />
        <File name="homer_disappear" src="html_src/public/img/homer_disappear.gif" />
        <File name="horrified" src="html_src/public/img/horrified.png" />
        <File name="how_about_sloth" src="html_src/public/img/how_about_sloth.gif" />
        <File name="hulk" src="html_src/public/img/hulk.png" />
        <File name="hypnotoad" src="html_src/public/img/hypnotoad.gif" />
        <File name="illuminati_confirmed" src="html_src/public/img/illuminati_confirmed.png" />
        <File name="in_n_out" src="html_src/public/img/in_n_out.jpg" />
        <File name="infinity" src="html_src/public/img/infinity.png" />
        <File name="instagram" src="html_src/public/img/instagram.png" />
        <File name="invisible_parrot" src="html_src/public/img/invisible_parrot.gif" />
        <File name="j_scrabble" src="html_src/public/img/j_scrabble.jpg" />
        <File name="jar_jar_binks" src="html_src/public/img/jar_jar_binks.png" />
        <File name="jedi_parrot" src="html_src/public/img/jedi_parrot.gif" />
        <File name="jetpacktocat" src="html_src/public/img/jetpacktocat.png" />
        <File name="jira" src="html_src/public/img/jira.png" />
        <File name="jung_von_matt" src="html_src/public/img/jung_von_matt.jpg" />
        <File name="kakao_angry_peach" src="html_src/public/img/kakao_angry_peach.png" />
        <File name="kakao_apeach_dance" src="html_src/public/img/kakao_apeach_dance.png" />
        <File name="kakao_give_up_on_life" src="html_src/public/img/kakao_give_up_on_life.png" />
        <File name="kakao_nooo" src="html_src/public/img/kakao_nooo.png" />
        <File name="kakao_sassy" src="html_src/public/img/kakao_sassy.png" />
        <File name="kakao_sorry" src="html_src/public/img/kakao_sorry.png" />
        <File name="kakao_tick_tock" src="html_src/public/img/kakao_tick_tock.png" />
        <File name="kermit_tea" src="html_src/public/img/kermit_tea.png" />
        <File name="kewl" src="html_src/public/img/kewl.gif" />
        <File name="khan" src="html_src/public/img/khan.gif" />
        <File name="kilt_bagpipe" src="html_src/public/img/kilt_bagpipe.png" />
        <File name="koolaid_man" src="html_src/public/img/koolaid_man.png" />
        <File name="lacroix" src="html_src/public/img/lacroix.png" />
        <File name="lalala" src="html_src/public/img/lalala.gif" />
        <File name="limecat" src="html_src/public/img/limecat.png" />
        <File name="link_catch" src="html_src/public/img/link_catch.jpg" />
        <File name="link_wave" src="html_src/public/img/link_wave.png" />
        <File name="love_parrot" src="html_src/public/img/love_parrot.gif" />
        <File name="luxemburgerli" src="html_src/public/img/luxemburgerli.png" />
        <File name="make_it_so" src="html_src/public/img/make_it_so.gif" />
        <File name="make_it_work" src="html_src/public/img/make_it_work.jpg" />
        <File name="mario" src="html_src/public/img/mario.gif" />
        <File name="mcgonagall_clapping" src="html_src/public/img/mcgonagall_clapping.gif" />
        <File name="meerkat" src="html_src/public/img/meerkat.gif" />
        <File name="mic_drop" src="html_src/public/img/mic_drop.gif" />
        <File name="microsoft" src="html_src/public/img/microsoft.jpg" />
        <File name="middle_parrot" src="html_src/public/img/middle_parrot.gif" />
        <File name="mighty_mouse" src="html_src/public/img/mighty_mouse.png" />
        <File name="mind_blown" src="html_src/public/img/mind_blown.gif" />
        <File name="most_interesting_man" src="html_src/public/img/most_interesting_man.png" />
        <File name="murrica" src="html_src/public/img/murrica.jpg" />
        <File name="my_little_octocat" src="html_src/public/img/my_little_octocat.png" />
        <File name="n64" src="html_src/public/img/n64.gif" />
        <File name="neo" src="html_src/public/img/neo.png" />
        <File name="nike_swoosh" src="html_src/public/img/nike_swoosh.png" />
        <File name="ninja" src="html_src/public/img/ninja.gif" />
        <File name="ninja_turtle" src="html_src/public/img/ninja_turtle.png" />
        <File name="no" src="html_src/public/img/no.png" />
        <File name="no_dice" src="html_src/public/img/no_dice.png" />
        <File name="nope-min" src="html_src/public/img/nope-min.gif" />
        <File name="nope" src="html_src/public/img/nope.gif" />
        <File name="nope_nope_nope" src="html_src/public/img/nope_nope_nope.gif" />
        <File name="npm" src="html_src/public/img/npm.png" />
        <File name="nyan_parrot" src="html_src/public/img/nyan_parrot.gif" />
        <File name="octocat" src="html_src/public/img/octocat.png" />
        <File name="octocat_gentleman_dev" src="html_src/public/img/octocat_gentleman_dev.jpg" />
        <File name="octocat_lady_dev" src="html_src/public/img/octocat_lady_dev.png" />
        <File name="octocat_lady_dev_brunette" src="html_src/public/img/octocat_lady_dev_brunette.png" />
        <File name="oktobercat" src="html_src/public/img/oktobercat.png" />
        <File name="on_off_switch" src="html_src/public/img/on_off_switch.jpg" />
        <File name="one_does_not_simply" src="html_src/public/img/one_does_not_simply.png" />
        <File name="opera" src="html_src/public/img/opera.png" />
        <File name="papal_parrot" src="html_src/public/img/papal_parrot.gif" />
        <File name="paraglider" src="html_src/public/img/paraglider.png" />
        <File name="parrot_lift_off" src="html_src/public/img/parrot_lift_off.gif" />
        <File name="party_aw_yeah" src="html_src/public/img/party_aw_yeah.gif" />
        <File name="party_corgi" src="html_src/public/img/party_corgi.gif" />
        <File name="party_crying_blood" src="html_src/public/img/party_crying_blood.gif" />
        <File name="party_dinosaur" src="html_src/public/img/party_dinosaur.gif" />
        <File name="party_docker" src="html_src/public/img/party_docker.gif" />
        <File name="party_dumpster_fire" src="html_src/public/img/party_dumpster_fire.gif" />
        <File name="party_frog" src="html_src/public/img/party_frog.gif" />
        <File name="party_otter_dance" src="html_src/public/img/party_otter_dance.gif" />
        <File name="party_porg" src="html_src/public/img/party_porg.gif" />
        <File name="party_trash_dove" src="html_src/public/img/party_trash_dove.gif" />
        <File name="party_turtle" src="html_src/public/img/party_turtle.gif" />
        <File name="party_wizard" src="html_src/public/img/party_wizard.gif" />
        <File name="pepe" src="html_src/public/img/pepe.png" />
        <File name="pepechu" src="html_src/public/img/pepechu.jpg" />
        <File name="philosoraptor" src="html_src/public/img/philosoraptor.png" />
        <File name="pillow" src="html_src/public/img/pillow.jpg" />
        <File name="pink_troll" src="html_src/public/img/pink_troll.png" />
        <File name="pinky_up" src="html_src/public/img/pinky_up.gif" />
        <File name="plus_one" src="html_src/public/img/plus_one.png" />
        <File name="pope" src="html_src/public/img/pope.png" />
        <File name="pope_francis" src="html_src/public/img/pope_francis.png" />
        <File name="portal_parrot" src="html_src/public/img/portal_parrot.gif" />
        <File name="postgresql" src="html_src/public/img/postgresql.png" />
        <File name="pug" src="html_src/public/img/pug.gif" />
        <File name="pumpkin_parrot" src="html_src/public/img/pumpkin_parrot.gif" />
        <File name="pusheen_dancing" src="html_src/public/img/pusheen_dancing.gif" />
        <File name="python" src="html_src/public/img/python.png" />
        <File name="raccoon_water_harp" src="html_src/public/img/raccoon_water_harp.gif" />
        <File name="rage" src="html_src/public/img/rage.jpg" />
        <File name="raised_eyebrow" src="html_src/public/img/raised_eyebrow.png" />
        <File name="raptor_disagrees" src="html_src/public/img/raptor_disagrees.gif" />
        <File name="react" src="html_src/public/img/react.png" />
        <File name="red_siren" src="html_src/public/img/red_siren.gif" />
        <File name="release_the_kraken" src="html_src/public/img/release_the_kraken.gif" />
        <File name="reverse_aussie_conga_parrot" src="html_src/public/img/reverse_aussie_conga_parrot.gif" />
        <File name="reverse_conga_parrot" src="html_src/public/img/reverse_conga_parrot.gif" />
        <File name="revolution_parrot" src="html_src/public/img/revolution_parrot.gif" />
        <File name="rickshaw" src="html_src/public/img/rickshaw.gif" />
        <File name="rock_nod" src="html_src/public/img/rock_nod.gif" />
        <File name="round_of_applause" src="html_src/public/img/round_of_applause.gif" />
        <File name="rubber-stamp" src="html_src/public/img/rubber-stamp.png" />
        <File name="rubber_duck" src="html_src/public/img/rubber_duck.png" />
        <File name="sad_pepe" src="html_src/public/img/sad_pepe.png" />
        <File name="safari" src="html_src/public/img/safari.png" />
        <File name="sailor_pusheen" src="html_src/public/img/sailor_pusheen.gif" />
        <File name="salmon_says" src="html_src/public/img/salmon_says.jpg" />
        <File name="saltbae" src="html_src/public/img/saltbae.gif" />
        <File name="salute" src="html_src/public/img/salute.png" />
        <File name="saturo" src="html_src/public/img/saturo.jpg" />
        <File name="science_parrot" src="html_src/public/img/science_parrot.gif" />
        <File name="shaka" src="html_src/public/img/shaka.png" />
        <File name="shakespeare" src="html_src/public/img/shakespeare.png" />
        <File name="shaking_angry_fist" src="html_src/public/img/shaking_angry_fist.gif" />
        <File name="ship_it_parrot" src="html_src/public/img/ship_it_parrot.gif" />
        <File name="shipping_shipping_ships" src="html_src/public/img/shipping_shipping_ships.jpg" />
        <File name="sith_parrot" src="html_src/public/img/sith_parrot.gif" />
        <File name="skateboarding" src="html_src/public/img/skateboarding.jpg" />
        <File name="skeptical" src="html_src/public/img/skeptical.png" />
        <File name="sketch" src="html_src/public/img/sketch.png" />
        <File name="ski_parrot" src="html_src/public/img/ski_parrot.gif" />
        <File name="snapchat" src="html_src/public/img/snapchat.jpg" />
        <File name="snow_octocat" src="html_src/public/img/snow_octocat.png" />
        <File name="sonic" src="html_src/public/img/sonic.gif" />
        <File name="sonic_waiting" src="html_src/public/img/sonic_waiting.gif" />
        <File name="sonos" src="html_src/public/img/sonos.png" />
        <File name="spicey" src="html_src/public/img/spicey.png" />
        <File name="spotify" src="html_src/public/img/spotify.png" />
        <File name="stable_parrot" src="html_src/public/img/stable_parrot.gif" />
        <File name="stack_overflow" src="html_src/public/img/stack_overflow.png" />
        <File name="starfleet" src="html_src/public/img/starfleet.png" />
        <File name="stop" src="html_src/public/img/stop.gif" />
        <File name="stop_sign" src="html_src/public/img/stop_sign.png" />
        <File name="success-kid" src="html_src/public/img/success-kid.png" />
        <File name="such_semantic" src="html_src/public/img/such_semantic.jpg" />
        <File name="super_girl" src="html_src/public/img/super_girl.png" />
        <File name="superman" src="html_src/public/img/superman.gif" />
        <File name="superman_sheild" src="html_src/public/img/superman_sheild.jpg" />
        <File name="swiss-fondue" src="html_src/public/img/swiss-fondue.png" />
        <File name="tableflip" src="html_src/public/img/tableflip.gif" />
        <File name="taion" src="html_src/public/img/taion.png" />
        <File name="take_my_money" src="html_src/public/img/take_my_money.png" />
        <File name="teamwork" src="html_src/public/img/teamwork.png" />
        <File name="that" src="html_src/public/img/that.gif" />
        <File name="this" src="html_src/public/img/this.gif" />
        <File name="this_is_a_wug" src="html_src/public/img/this_is_a_wug.gif" />
        <File name="this_is_fine" src="html_src/public/img/this_is_fine.png" />
        <File name="thumbsup_parrot" src="html_src/public/img/thumbsup_parrot.gif" />
        <File name="tiziana" src="html_src/public/img/tiziana.jpg" />
        <File name="totes_magoats" src="html_src/public/img/totes_magoats.gif" />
        <File name="totoro" src="html_src/public/img/totoro.gif" />
        <File name="train_wreck" src="html_src/public/img/train_wreck.gif" />
        <File name="transparront" src="html_src/public/img/transparront.gif" />
        <File name="trap" src="html_src/public/img/trap.png" />
        <File name="trex" src="html_src/public/img/trex.gif" />
        <File name="troll" src="html_src/public/img/troll.png" />
        <File name="troll_doll" src="html_src/public/img/troll_doll.png" />
        <File name="troll_parrot" src="html_src/public/img/troll_parrot.gif" />
        <File name="trolldance" src="html_src/public/img/trolldance.gif" />
        <File name="tumbleweed" src="html_src/public/img/tumbleweed.gif" />
        <File name="twitter" src="html_src/public/img/twitter.png" />
        <File name="verified" src="html_src/public/img/verified.png" />
        <File name="wacky_waving_inflatable_tube_man" src="html_src/public/img/wacky_waving_inflatable_tube_man.gif" />
        <File name="wacky_waving_inflatable_tube_man_america" src="html_src/public/img/wacky_waving_inflatable_tube_man_america.gif" />
        <File name="wacky_waving_inflatable_tube_man_salmon" src="html_src/public/img/wacky_waving_inflatable_tube_man_salmon.gif" />
        <File name="watch_out" src="html_src/public/img/watch_out.png" />
        <File name="webpack" src="html_src/public/img/webpack.png" />
        <File name="whoa" src="html_src/public/img/whoa.jpg" />
        <File name="witness_protection_parrot" src="html_src/public/img/witness_protection_parrot.gif" />
        <File name="wonder_woman" src="html_src/public/img/wonder_woman.jpg" />
        <File name="wtf_jackie_chan" src="html_src/public/img/wtf_jackie_chan.jpg" />
        <File name="ya_rly" src="html_src/public/img/ya_rly.png" />
        <File name="yes" src="html_src/public/img/yes.png" />
        <File name="yes_sir" src="html_src/public/img/yes_sir.gif" />
        <File name="yo_dawg" src="html_src/public/img/yo_dawg.png" />
        <File name="yoda" src="html_src/public/img/yoda.jpeg" />
        <File name="yoshi" src="html_src/public/img/yoshi.gif" />
        <File name="youtube" src="html_src/public/img/youtube.png" />
        <File name="zeplin" src="html_src/public/img/zeplin.png" />
        <File name="zoidberg" src="html_src/public/img/zoidberg.jpg" />
        <File name="init" src="html_src/public/js/init.js" />
        <File name="jquery.min" src="html_src/public/js/jquery.min.js" />
        <File name="robotutils" src="html_src/public/js/robotutils.js" />
        <File name="webpack.config" src="html_src/webpack.config.js" />
        <File name="yarn-error" src="html_src/yarn-error.log" />
        <File name="yarn" src="html_src/yarn.lock" />
        <File name="reacting_to_events" src="python/reacting_to_events.py" />
    </Resources>
    <Topics>
        <Topic name="dlg_welcome_enu" src="dlg_welcome/dlg_welcome_enu.top" topicName="dlg_welcome" language="en_US" />
    </Topics>
    <IgnoredPaths />
    <Translations auto-fill="en_US">
        <Translation name="translation_en_US" src="translations/translation_en_US.ts" language="en_US" />
    </Translations>
</Package>
